Dev 16940 1
productsupcom/bin-cde-shopify-metafields pull request #8
Opened 2024-04-16 15:45 UTC by khelmrich

### Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change. And don't forget to add the related Jira Issue ID (e.g.
DEV-7327). Swarmia adding then automatically the link to the PR.

### Checklist:

- [ ] All acceptance criteria/requirements are met
- [ ] New/updated functionality is covered by tests
- [ ] All tests have been successfully run
- [ ] CI run has passed all checks
- [ ] My code follows the style guidelines of this project
- [ ] Any dependent changes have been merged and released in downstream modules
- [ ] Single feature has passed QA on local environment
- [ ] The initial request has approved/reviewed changes

2024-04-18 11:54 UTC, jacekgadomski approved these changes
🔥  nice i like it, needs some minor improvements

2024-04-18 11:54 UTC, jacekgadomski commented on .env.test
>  APP_SECRET='$ecretf0rt3st'
pls check if APP_SECRET, SYMFONY_DEPRECATIONS_HELPER and PANTHER_APP_ENV is needed if not pls remove it

2024-04-18 11:54 UTC, jacekgadomski commented on composer.json
> +        "productsupcom/dk-core-bundle": "dev-jane-7-upgrade",
pls change to at least v0.0.*

2024-04-18 11:54 UTC, jacekgadomski commented on composer.json
> +        "productsupcom/dk-core-bundle": "dev-jane-7-upgrade",
hehe and add composer.lock to the project

2024-04-18 11:54 UTC, jacekgadomski commented on config/services.yaml
> +            $username: 'test'
i would leave it as empty string '' instead test, it suggest that those are test values but they are not

2024-04-18 11:54 UTC, jacekgadomski commented on config/services.yaml
> +            $password: 'test'
same here

2024-04-18 11:54 UTC, jacekgadomski commented on config/services.yaml
> +    Productsup\DK\Connector\Application\Progress\CountableProgressHandler: ~
check if needed if it is in the bundle, if it is not the add it pls, if there is one common interface for progress handlers then do not add it and leave it as it is

2024-04-18 11:54 UTC, jacekgadomski commented on src/Export/Infrastructure/Uploader/DataBuffer.php
> +
i think class like this is int he bundle/library and you can use it, instead of your own implementation

2024-04-18 11:54 UTC, jacekgadomski commented on src/Export/Infrastructure/Http/Response/Handler.php
> +final readonly class Handler
what handler?

2024-04-18 11:54 UTC, jacekgadomski commented on src/Export/Infrastructure/Http/Response/Handler.php
> +        if (isset($responseData['data']['metafieldsSet']['userErrors'])) {
i would invert condition to have foreach outside of if, imo more readable

2024-04-18 11:54 UTC, jacekgadomski commented on src/Export/Infrastructure/Http/Exception/Handler.php
> +final class Handler
what handler

2024-04-18 11:54 UTC, jacekgadomski commented on src/Export/Infrastructure/Uploader/MetafieldUploader.php
> +namespace Productsup\BinCdeShopifyMetafields\Export\Infrastructure\Uploader;
some empty lines between methods are missing

2024-04-18 11:54 UTC, jacekgadomski commented on src/Export/Infrastructure/Uploader/MetafieldUploader.php
> +            $response = $this->client->request('POST', '/admin/api/2024-01/graphql.json', [
pls add interface for uploader, it should go to application layer or to domain
use interface instead of this class in metafieldhandler

2024-04-18 11:54 UTC, jacekgadomski commented on src/Export/Builder/ContentBuilder.php
> +
this class and whole directory should go to infrastructure somewhere near to the client i think?

2024-04-18 11:54 UTC, jacekgadomski requested changes
🔥 nice i like it, needs some minor improvements

2024-04-18 13:01 UTC, khelmrich commented on src/Export/Infrastructure/Uploader/DataBuffer.php
> +
this class does not meet my requirements. I will create separate ticket to add new type of buffer in lib :)

2024-04-19 10:19 UTC, khelmrich commented on config/services.yaml
> +            $username: 'test'
done

2024-04-19 10:23 UTC, khelmrich commented on config/services.yaml
> +    Productsup\DK\Connector\Application\Progress\CountableProgressHandler: ~
progress handler is not added to the bundle. Without this I was not able to run composer update. We spoke about this, you mentioned that not everything should be set up in the bundle. Should this be in the bundle?

2024-04-19 10:27 UTC, khelmrich commented on src/Export/Infrastructure/Http/Response/Handler.php
> +final readonly class Handler
renamed

2024-04-19 10:35 UTC, khelmrich commented on src/Export/Infrastructure/Uploader/MetafieldUploader.php
> +namespace Productsup\BinCdeShopifyMetafields\Export\Infrastructure\Uploader;
done

2024-04-19 10:40 UTC, khelmrich commented on src/Export/Infrastructure/Uploader/MetafieldUploader.php
> +            $response = $this->client->request('POST', '/admin/api/2024-01/graphql.json', [
done

2024-04-19 10:41 UTC, khelmrich commented on src/Export/Builder/ContentBuilder.php
> +
yes you are right should be in different place

2024-04-22 12:15 UTC, khelmrich commented on src/Export/Infrastructure/Http/Response/Handler.php
> +        if (isset($responseData['data']['metafieldsSet']['userErrors'])) {
changed this

2024-04-26 06:36 UTC, jacekgadomski commented on config/services.yaml
> +    Productsup\DK\Connector\Application\Progress\CountableProgressHandler: ~
I would have to take a look

2024-04-26 06:42 UTC, jacekgadomski requested changes
almost, pls fix json exceptions handling, if you need guidance pls ask

2024-04-26 06:42 UTC, jacekgadomski commented on src/Export/Infrastructure/Uploader/MetafieldUploader.php
> +            $this->responseHandler->handle(json_decode($response->getBody()->getContents(), true), $data, $metafield);
exeptions are not properly handled, ie: json is not handled

2024-04-26 06:42 UTC, jacekgadomski commented on src/Export/Application/Feedback/Feedback.php
> +            'metafield' => json_encode($this->metafield),
json exception not handled

2024-04-26 08:06 UTC, khelmrich commented on src/Export/Infrastructure/Uploader/MetafieldUploader.php
> +            $this->responseHandler->handle(json_decode($response->getBody()->getContents(), true), $data, $metafield);
json exception added

2024-04-26 08:06 UTC, khelmrich commented on src/Export/Application/Feedback/Feedback.php
> +            'metafield' => json_encode($this->metafield),
added

2024-04-26 08:09 UTC, kamil-fityka approved these changes

2024-04-26 08:18 UTC, jacekgadomski approved these changes
🔥

2024-04-26 08:18 UTC, merged